/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import mundo.Empleado;

/**
 *
 * @author nicoa
 */
public class InterfazNomina extends javax.swing.JFrame {

    //Variable global para almacenar los descuentos realizados
    private Float descuentosRealizados = 0F;

    // Salario base
    private Float salarioBase = 0F;

    /**
     * Creates new form InterfazNomina
     */
    public InterfazNomina() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDEmpleadonom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonNuevaConsulta = new javax.swing.JButton();
        botonRegresa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonConsulta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        checkDescuentoFSP = new javax.swing.JCheckBox();
        checkDescuentoEPS = new javax.swing.JCheckBox();
        checkDescuentoAusencia = new javax.swing.JCheckBox();
        checkRetencionFuente = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreadeSalario = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        salarioaPagar = new javax.swing.JTextArea();
        saldoaPagar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        heDiurna = new javax.swing.JTextField();
        heNocturna = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sección de Pagos de Nomina");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Consulta de Pagos de Nomina de Empleados");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID de empleado:");

        IDEmpleadonom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEmpleadonomActionPerformed(evt);
            }
        });
        IDEmpleadonom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDEmpleadonomKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Salario Base:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Salario a Pagar:");

        botonNuevaConsulta.setText("NUEVA CONSULTA");
        botonNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaConsultaActionPerformed(evt);
            }
        });

        botonRegresa.setText("REGRESAR");
        botonRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contabilidad.png"))); // NOI18N

        botonConsulta.setText("CONSULTAR");
        botonConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultaMouseClicked(evt);
            }
        });
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Deducciones"));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        checkDescuentoFSP.setText("Descuento FSP");
        checkDescuentoFSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkDescuentoFSPMouseClicked(evt);
            }
        });

        checkDescuentoEPS.setText("Descuento EPS");
        checkDescuentoEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkDescuentoEPSMouseClicked(evt);
            }
        });
        checkDescuentoEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDescuentoEPSActionPerformed(evt);
            }
        });

        checkDescuentoAusencia.setText("Descuento ausencia");
        checkDescuentoAusencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkDescuentoAusenciaMouseClicked(evt);
            }
        });
        checkDescuentoAusencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDescuentoAusenciaActionPerformed(evt);
            }
        });

        checkRetencionFuente.setText("Retención de fuente");
        checkRetencionFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkRetencionFuenteMouseClicked(evt);
            }
        });
        checkRetencionFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRetencionFuenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkDescuentoEPS)
                        .addGap(18, 18, 18)
                        .addComponent(checkRetencionFuente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkDescuentoFSP)
                        .addGap(18, 18, 18)
                        .addComponent(checkDescuentoAusencia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDescuentoFSP)
                    .addComponent(checkDescuentoAusencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDescuentoEPS)
                    .addComponent(checkRetencionFuente))
                .addGap(20, 20, 20))
        );

        AreadeSalario.setEditable(false);
        AreadeSalario.setColumns(1);
        AreadeSalario.setRows(1);
        jScrollPane1.setViewportView(AreadeSalario);

        salarioaPagar.setEditable(false);
        salarioaPagar.setColumns(1);
        salarioaPagar.setRows(1);
        jScrollPane2.setViewportView(salarioaPagar);

        saldoaPagar.setText("CONSULTAR SALARIO A PAGAR");
        saldoaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoaPagarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas Extras"));

        jLabel6.setText("Horas extras diurnas");

        jLabel7.setText("Horas extras nocturnas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heNocturna)
                    .addComponent(heDiurna, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(heDiurna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(heNocturna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(botonNuevaConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(saldoaPagar)
                                .addGap(191, 191, 191)
                                .addComponent(botonRegresa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(102, 102, 102)))
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IDEmpleadonom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(botonConsulta)))
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDEmpleadonom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(saldoaPagar)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRegresa)
                            .addComponent(botonNuevaConsulta))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresaActionPerformed
        InterfazPrincipal frame = new InterfazPrincipal();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_botonRegresaActionPerformed

    private void botonNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaConsultaActionPerformed
        IDEmpleadonom.setText("");
        AreadeSalario.setText("");
        checkDescuentoFSP.setSelected(false);
        checkDescuentoAusencia.setSelected(false);
        checkDescuentoEPS.setSelected(false);
        checkRetencionFuente.setSelected(false);
        buttonGroup1.clearSelection();
        salarioaPagar.setText("");
        heDiurna.setText("");
        heNocturna.setText("");
        checkDescuentoAusencia.setEnabled(true); 
        checkDescuentoEPS.setEnabled(true);
        checkRetencionFuente.setEnabled(true);
        checkDescuentoFSP.setEnabled(true);
        descuentosRealizados = 0F;
    }//GEN-LAST:event_botonNuevaConsultaActionPerformed

    private void IDEmpleadonomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEmpleadonomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEmpleadonomActionPerformed

    private void IDEmpleadonomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDEmpleadonomKeyTyped
        if (IDEmpleadonom.getText().length() >= 7) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (IDEmpleadonom.getText().trim().length() == 7) {
            evt.consume();
        }

    }//GEN-LAST:event_IDEmpleadonomKeyTyped

    private void botonConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultaMouseClicked
        if (IDEmpleadonom.getText().isEmpty()) {
            botonConsulta.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Botón deshabilitado. "
                    + "Asegurese de ingresar el ID del empleado. "
                    + "Una vez llenado el campo, intente nuevamente para reactivar el botón");
        } else {
            botonConsulta.setEnabled(true);
        }
    }//GEN-LAST:event_botonConsultaMouseClicked

    private void checkDescuentoFSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkDescuentoFSPMouseClicked
        if (checkDescuentoFSP.isEnabled() && checkDescuentoFSP.isSelected()) {
            descuento();
            checkDescuentoFSP.setEnabled(false);
        }
    }//GEN-LAST:event_checkDescuentoFSPMouseClicked

    private void checkDescuentoAusenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkDescuentoAusenciaMouseClicked
        if (checkDescuentoAusencia.isEnabled() && checkDescuentoAusencia.isSelected()) {
            descuento();
            checkDescuentoAusencia.setEnabled(false);
        }
    }//GEN-LAST:event_checkDescuentoAusenciaMouseClicked

    private void checkDescuentoEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkDescuentoEPSMouseClicked
        if (checkDescuentoEPS.isEnabled() && checkDescuentoEPS.isSelected()) {
            descuento();
            checkDescuentoEPS.setEnabled(false);
        }
    }//GEN-LAST:event_checkDescuentoEPSMouseClicked

    private void checkRetencionFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkRetencionFuenteMouseClicked
        if (checkRetencionFuente.isEnabled() && checkRetencionFuente.isSelected()) {
            descuento();
            checkRetencionFuente.setEnabled(false);
        }
    }//GEN-LAST:event_checkRetencionFuenteMouseClicked

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        try {
            // busca la cuenta y la devuelve
            String idEmp = IDEmpleadonom.getText() != null && !IDEmpleadonom.getText().isEmpty() ? IDEmpleadonom.getText(): "0";
            Empleado emp = InterfazPrincipal.TabladeEmpleados.queryForId(Integer.parseInt(idEmp));
            // Se imprime la información en el Area de Texto
            if (emp == null) {
                JOptionPane.showMessageDialog(null, "No se encuentra el empleado con el criterio de busqueda",
                        "Mensaje", JOptionPane.WARNING_MESSAGE);
                this.AreadeSalario.setText("");
                return;
            }
            // Se imprime la información en el Area de Texto
            StringBuilder sb = new StringBuilder();
            sb.append(emp.getSalariobase());
            AreadeSalario.setText(sb.toString());
            String valorSalarioBase = sb.toString();
            if (valorSalarioBase != null && !valorSalarioBase.isEmpty()) {
                this.salarioBase = Float.parseFloat(valorSalarioBase);
            } else {
                this.salarioBase = 0F;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "El empleado no pudo ser localizado, intente nuevamente");
        }
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void saldoaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoaPagarActionPerformed
        /*
          Se procede a tomar las horas extras nocturnas y diurnas Calcular el
          valor a pagar por horas extras dependiendo del salario y restar las
          deducciones
         */
        String strHeDiurna = this.heDiurna.getText() != null && !this.heDiurna.getText().isEmpty() ? this.heDiurna.getText() : "0";
        String strHeNocturna = this.heNocturna.getText() != null && !this.heNocturna.getText().isEmpty() ? this.heNocturna.getText() : "0";
        Integer totalHEDiurna = Integer.parseInt(strHeDiurna);
        Integer totalHENocturna = Integer.parseInt(strHeNocturna);
        Float valorHora = this.salarioBase / 30 / 8;
        Double recargoHED = (valorHora * 0.25) + valorHora;
        Double recargoHEN = (valorHora * 0.75) + valorHora;
        Double valorCalcHEDiurna = recargoHED * totalHEDiurna;
        Double valorCalcHENocturna = recargoHEN * totalHENocturna;
        Double valorPagarHorasExtras = valorCalcHEDiurna + valorCalcHENocturna;

        Double resultadoAPagar = this.salarioBase + valorPagarHorasExtras - this.descuentosRealizados;
        this.salarioaPagar.setText(resultadoAPagar.toString());
    }//GEN-LAST:event_saldoaPagarActionPerformed

    private void checkDescuentoEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDescuentoEPSActionPerformed

    }//GEN-LAST:event_checkDescuentoEPSActionPerformed

    private void checkRetencionFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRetencionFuenteActionPerformed

    }//GEN-LAST:event_checkRetencionFuenteActionPerformed

    private void checkDescuentoAusenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDescuentoAusenciaActionPerformed

    }//GEN-LAST:event_checkDescuentoAusenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfazNomina().setVisible(true);
        });
    }

    public float descuento() 
    {
        String valor = JOptionPane.showInputDialog("Ingrese la cantidad a descontar");
        if (valor != null) 
        {
            int input;
            if (valor.isEmpty()) {
                input = 0;
            } else {
                input = Integer.parseInt(valor);
            }
            this.descuentosRealizados += input;
            System.out.println("La suma de descuento => " + this.descuentosRealizados);
        }

        return this.descuentosRealizados;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreadeSalario;
    private javax.swing.JTextField IDEmpleadonom;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonNuevaConsulta;
    private javax.swing.JButton botonRegresa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkDescuentoAusencia;
    private javax.swing.JCheckBox checkDescuentoEPS;
    private javax.swing.JCheckBox checkDescuentoFSP;
    private javax.swing.JCheckBox checkRetencionFuente;
    private javax.swing.JTextField heDiurna;
    private javax.swing.JTextField heNocturna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea salarioaPagar;
    private javax.swing.JButton saldoaPagar;
    // End of variables declaration//GEN-END:variables
}
