/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import com.j256.ormlite.jdbc.JdbcConnectionSource;
import com.j256.ormlite.support.ConnectionSource;
import com.j256.ormlite.table.TableUtils;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import mundo.Empleado;

/**
 *
 * @author nicoa
 */
public class InterfazAgregaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAgregaEmpleado
     */
    public InterfazAgregaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreregistro = new javax.swing.JTextField();
        apellidoregistro = new javax.swing.JTextField();
        salarioregistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cargoBox = new javax.swing.JComboBox<>();
        comboHoras = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        botonAgregaEmpleadoNuevo = new javax.swing.JButton();
        botonRegresaEmpleadosPrincipal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        usuarioID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sección Agregar Empleado");
        setResizable(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Salario Base:");

        jLabel4.setText("Horas por contrato:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("AGREGAR EMPLEADOS A LA BASE DE DATOS DE LA COMPAÑIA");

        nombreregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreregistroKeyTyped(evt);
            }
        });

        apellidoregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoregistroKeyTyped(evt);
            }
        });

        salarioregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioregistroActionPerformed(evt);
            }
        });
        salarioregistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salarioregistroKeyTyped(evt);
            }
        });

        jLabel7.setText("Cargo:");

        cargoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>", "Asistente", "Desarrollador", "RRHH", "QA Tester Funcional", "QA Tester Automation", "Gerente", "Scrum Master", "Product Owner" }));
        cargoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoBoxActionPerformed(evt);
            }
        });

        comboHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Default>", "24", "35", "42", "48" }));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agrega empleado.jpg"))); // NOI18N

        botonAgregaEmpleadoNuevo.setText("AGREGAR");
        botonAgregaEmpleadoNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregaEmpleadoNuevoMouseClicked(evt);
            }
        });
        botonAgregaEmpleadoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaEmpleadoNuevoActionPerformed(evt);
            }
        });

        botonRegresaEmpleadosPrincipal.setText("REGRESAR");
        botonRegresaEmpleadosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresaEmpleadosPrincipalActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPIAR FORMULARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Usuario ID:");

        usuarioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioIDActionPerformed(evt);
            }
        });
        usuarioID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(487, 487, 487))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(apellidoregistro)
                                            .addComponent(nombreregistro)
                                            .addComponent(usuarioID)
                                            .addComponent(cargoBox, 0, 314, Short.MAX_VALUE)
                                            .addComponent(salarioregistro)
                                            .addComponent(comboHoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAgregaEmpleadoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(113, 113, 113)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonRegresaEmpleadosPrincipal)
                                .addGap(212, 212, 212))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(apellidoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cargoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(salarioregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregaEmpleadoNuevo)
                    .addComponent(botonRegresaEmpleadosPrincipal)
                    .addComponent(jButton1))
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresaEmpleadosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresaEmpleadosPrincipalActionPerformed
        InterfazEmpleados frame = new InterfazEmpleados();
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_botonRegresaEmpleadosPrincipalActionPerformed

    private void cargoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoBoxActionPerformed

    }//GEN-LAST:event_cargoBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Se limpian las cajas y se dejan en el index determinado las cajas
        usuarioID.setText("");
        nombreregistro.setText("");
        apellidoregistro.setText("");
        cargoBox.setSelectedIndex(0);
        salarioregistro.setText("");
        comboHoras.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioIDActionPerformed

    private void usuarioIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioIDKeyTyped
        /*Se escucha atentamente a las teclas seleccionadas. Utilziando ASCII se habilitan unicamente los números autorizados hasta un total de 7 digitos.
    Si el usuario selecciona otro caracter ya sea especial o letra tendremos el evt.consume() que descarta el caracter*/
        if (usuarioID.getText().length() >= 7) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (usuarioID.getText().trim().length() == 7) {
            evt.consume();
        }
    }//GEN-LAST:event_usuarioIDKeyTyped

    private void salarioregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioregistroActionPerformed

    private void salarioregistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioregistroKeyTyped
        /*Se escucha atentamente a las teclas seleccionadas. Utilziando ASCII se habilitan unicamente los números autorizados y el simbolo [.] hasta un total de 11 caracteres. 
    Si el usuario selecciona otro caracter ya sea especial o letra tendremos el evt.consume() que descarta el caracter*/
        if (salarioregistro.getText().length() >= 11) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57 || key == 46;

        if (!numeros) {
            evt.consume();
        }

        if (salarioregistro.getText().trim().length() == 11) {
            evt.consume();
        }
    }//GEN-LAST:event_salarioregistroKeyTyped

    private void nombreregistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreregistroKeyTyped
        /*Se escucha atentamente a las teclas seleccionadas. Utilziando ASCII se habilitan unicamente las letras hasta un total de 50 caracteres. 
        Si el usuario selecciona otro caracter ya sea especial o número tendremos el evt.consume() que descarta el caracter*/
        if (nombreregistro.getText().length() >= 30) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean letras = key >= 65 && key <= 90 || key >= 97 && key <= 122 || key == 32;

        if (!letras) {
            evt.consume();
        }

        if (nombreregistro.getText().trim().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreregistroKeyTyped

    private void apellidoregistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoregistroKeyTyped
        /*Se escucha atentamente a las teclas seleccionadas. Utilziando ASCII se habilitan unicamente las letras hasta un total de 50 caracteres. Si el usuario selecciona otro
        Si el usuario selecciona otro caracter ya sea especial o número tendremos el evt.consume() que descarta el caracter*/
        if (apellidoregistro.getText().length() >= 50) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean letras = key >= 65 && key <= 90 || key >= 97 && key <= 122 || key == 32;

        if (!letras) {
            evt.consume();
        }

        if (apellidoregistro.getText().trim().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_apellidoregistroKeyTyped

    private void botonAgregaEmpleadoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaEmpleadoNuevoActionPerformed

    }//GEN-LAST:event_botonAgregaEmpleadoNuevoActionPerformed

    private void botonAgregaEmpleadoNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregaEmpleadoNuevoMouseClicked
        // verifica si los campos de texto y cajas contiene la información requerida para hacer el registro. Si alguno esta vacio este se deshabilita de lo contrario el botón estará activado
        if (usuarioID.getText().isEmpty() || nombreregistro.getText().isEmpty() || apellidoregistro.getText().isEmpty() || salarioregistro.getText().isEmpty() || cargoBox.getSelectedIndex() == 0 || comboHoras.getSelectedIndex() == 0) {
            botonAgregaEmpleadoNuevo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Botón deshabilitado, asegurese de ingresar toda la información e intente nuevamente presionando el botón para reactivarlo");
        } else {
            botonAgregaEmpleadoNuevo.setEnabled(true);

            // Una vez verificada la información del empleado, este tomará la información de los jtextBox y los agregara a la base de datos. 
            Empleado e = new Empleado(Integer.parseInt(usuarioID.getText()), nombreregistro.getText(), apellidoregistro.getText(), cargoBox.getSelectedItem().toString(), Float.parseFloat(salarioregistro.getText()), comboHoras.getSelectedItem().toString());
            try {
                InterfazPrincipal.TabladeEmpleados.create(e);
                JOptionPane.showMessageDialog(null, "Empleado agregado exitosamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en el sistema, el empleado no se ha agregado correctamente");
            }

        }

    }//GEN-LAST:event_botonAgregaEmpleadoNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgregaEmpleado().setVisible(true);
                // Se crea la conexión a la base de datos
                ConnectionSource conexion;
                // Se requiere una url para la base de datos generada localmente dentro del proyecto
                String url = "jdbc:h2:file:./data/misempleados";
                // Se realiza la conexion de la base de datos a la URL                

                try {
                    conexion = new JdbcConnectionSource(url);
                    System.out.println("Conexión realizada!");
                    // Se crea efectivamente la tabla
                    TableUtils.createTable(conexion, Empleado.class);
                    System.out.println("Tabla creada");
                    conexion.close();
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                } 
                catch (Exception e) {
                    Logger.getLogger(InterfazAgregaEmpleado.class.getName()).log(Level.SEVERE, null, e);
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                }

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoregistro;
    private javax.swing.JButton botonAgregaEmpleadoNuevo;
    private javax.swing.JButton botonRegresaEmpleadosPrincipal;
    private javax.swing.JComboBox<String> cargoBox;
    private javax.swing.JComboBox<String> comboHoras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreregistro;
    private javax.swing.JTextField salarioregistro;
    private javax.swing.JTextField usuarioID;
    // End of variables declaration//GEN-END:variables
}
